delay: 60
workers:
  indexing:
    spawner:
      command:
        - zsh
        - -c
        - "{{queues}} bundle exec rake resque:work"
      dir: /my/work/dir
      env:
        rails_env: development
        rbenv_version: 1.9.3-p194
    wait_time: 120
    threshold: 100
    spawn_rate: 1
    remove_when_idle: true
    queues:
      - queue_the_first
      - queue_tee_pie
      - queue_the_music
    pool:
      global_max: 15
      min: 2
      max: 5
      first_at: 1